### ISSUE TITLE
Include C Examples

### ISSUE THREAD

**Issue by mmstick** [varlink/libvarlink#11]
There's some statistical evidence that most programmers evaluate, and learn how to use, libraries by their examples included with the project. So, it would be a good idea to include some examples for the C library so that C program authors will have a good idea about what's involved in getting this integrated with their projects.

**Comment by afbjorklund** [comment]
Here is one example: https://github.com/cherry-pick/com.redhat.resolver/tree/master/src

But something more "hello world" would probably be a good idea to include as documentation.

**Comment by cyclopsian** [comment]
It's not mentioned in readme, but the tests feature several examples. The server-client example is the most complete: [test-server-client.c](https://github.com/varlink/libvarlink/blob/master/lib/test-server-client.c)

**Comment by haraldh** [comment]
added to README
