### ISSUE TITLE
deprecated or not?

### ISSUE THREAD

**Issue by tyll** [varlink/libvarlink#25]
https://podman.io/blogs/2020/08/01/deprecate-and-remove-varlink-notice.html states "About one year ago, the Podman team was notified that the varlink library was being deprecated and there would be no further development and little support for it from the varlink library team." but not such notice is visible here or on https://varlink.org/. It would be great to clarify this.

**Comment by tyll** [comment]
If it is indeed deprecated, are there any recommended alternatives?

**Comment by haraldh** [comment]
It is not deprecated, and we did not notify anybody with such message.
