### ISSUE TITLE
Allow lsiting service with varlink tool

### ISSUE THREAD

**Issue by fabiand** [varlink/libvarlink#3]
`varlink <tab><tab>` allows identifying local services, but for convenience (and discoverability) `varlink ls` or alike would be nice.

**Comment by bl33pbl0p** [comment]
It seems to use the resolver for this purpose, hence you could easily get this information by doing:
`varlink call org.varlink.resolver.GetInfo | jq '.interfaces'`.

**Comment by fabiand** [comment]
I'm probably just aslking for a shorthand for this :)

**Comment by kaysievers** [comment]
Hmm, maybe we could make "$ varlink info" (without an address given) print all interfaces the resolver knows?

**Comment by fabiand** [comment]
Would work for me.

**Comment by kaysievers** [comment]
$ varlink resolve prints the list if interfaces now:
https://github.com/varlink/libvarlink/commit/58e82a5dbbd7f4c9bfcdd4aab3d0919561948317
