### ISSUE TITLE
grpc?

### ISSUE THREAD

**Issue by fabiand** [varlink/libvarlink#4]
Not that I am a fan of grpc - but how does varlink compare to it?

What benefits does valrink have which makes it so much better suited for the OS use-case?

**Comment by kaysievers** [comment]
Varlink aims to be the simplest possible still useful protocol:
  https://varlink.org/Ideals

It should be possible to use it even for in-kernel APIs as an alternative to custom subsystem filesystems, or /proc and /sys. We might never get there, but it's still the goal to allow this:
  https://varlink.org/Screenshots#kernel-module

No doubt, Grpc is useful, capable and has its place, but it is far too complicated for our goals, we really want dead-simple plain-text JSON, which everybody can read with just bstrace. :)

Varlink is more a "safe version" of the UNIX command-line options and stdout line printing, than it is D-Bus' or Grpc's binary marshaling. :)

**Comment by fabiand** [comment]
Thanks, that helps!
