### ISSUE TITLE
Please do a new release

### ISSUE THREAD

**Issue by cryptomilk** [varlink/libvarlink#65]
Could you please do a new release as this is blocking the inclusion of a varlink service to Samba.

See https://gitlab.com/samba-team/samba/-/merge_requests/2928

**Comment by cryptomilk** [comment]
@haraldh ^^

**Comment by cryptomilk** [comment]
@haraldh Any chance you find time for this? Thanks.

**Comment by haraldh** [comment]
https://github.com/varlink/libvarlink/releases/tag/24

**Comment by haraldh** [comment]
Thanks for nagging
