### ISSUE TITLE
Named PIPES as a backend

### ISSUE THREAD

**Issue by bl33pbl0p** [varlink/libvarlink#9]
Would it be possible to add named pipes/FIFOs as a transport for varlink (the ideals say any connection oriented transport can possibly work).

**Comment by kaysievers** [comment]
Varlink is a streaming protocol, and also has a strict message order. How would the service listening on a pipe deal with interleaving fragments of messages from multiple clients/connections?

**Comment by bl33pbl0p** [comment]
Hmm, maybe a different pipe for each connection? It does seem difficult, maybe this is not worth it, in that case, feel free to close the issue.
